config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "games#index"
  resources :games
  devise_scope :user do 
    get 'users/:id', to: 'users#show', as: 'user_profile'
  end

  resources :chat_rooms, only: [:show, :index]
  post :private_message, to: 'chat_rooms#private_message'
  resources :chat_messages, only: [:create]
  resources :games do
    resources :join_requests do
      member do
        post :create
        patch :accept
        patch :reject
      end
    end
    # post 'accept_join_request/:id', to: 'join_requests#accept', as: 'accept_join_request'
    # post 'reject_join_request/:id', to: 'join_requests#reject', as: 'reject_join_request'
  end
end

app/models/game.rb
class Game < ApplicationRecord
    validates :title, presence: true, length: { minimum: 4 }
    validates :description, presence: true, length: { minimum: 20 }
    validates :age_restriction, presence: true, inclusion: { in: ['18+', '16+', '12+', 'any'], 
        message: "%{value} is not a valid age restriction" }
    # validates :application_process, presence: true, length: { minimum: 20 }
    validates :recurrence, inclusion: { in: ['', 'one-shot', 'weekly', 'play-by-post', 'asynchronous', 'other'],
        message: "%{value} is not a valid recurrence" }

    has_and_belongs_to_many :users, join_table: 'games_users'
    belongs_to :dm, class_name: 'User', foreign_key: 'dm_id', optional: true

    has_one_attached :cover_image  
    belongs_to :gaming_system


    def self.ransackable_attributes(auth_object = nil)
        ["title", "description", "age_restriction", "gaming_system_id", 'next_occurrence', 'recurrence',
        'next_game', 'next_game_gteq', 'next_game_lteq', 'earliest_time', 'latest_time']
      end
      
      
      def self.ransackable_associations(auth_object = nil)
        ["gaming_system"]
      end
      # scope :next_game_date_gteq, ->(datetime) { where('next_game_date >= ?', datetime) }
      # scope :next_game_date_lteq, ->(datetime) { where('next_game_date <= ?', datetime) }
      has_many :join_requests, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

  def index
    @q = Game.ransack(params[:q])
    @games = @q.result.includes(:gaming_system)
    @gaming_systems = GamingSystem.order(priority: :desc, name: :asc)
    @age_restrictions = [['any', nil], ['12+', '12+'], ['18+', '18+']]
    @recurrences = [[], ['one-shot', 'one-shot'], ['weekly', 'weekly'], ['play-by-post', 'play-by-post'], ['other', 'other']]
  end

  def show
    @game = Game.find(params[:id])
    @dm = @game.dm
    @join_requests = @game.join_requests
  end

  def new
    @game = Game.new
    @gaming_systems = GamingSystem.order(priority: :desc, name: :asc)
  end

  def create
    @game = Game.new(game_params.except(:free, :gaming_system))
    @gaming_systems = GamingSystem.order(priority: :desc, name: :asc)
    @game.gaming_system = GamingSystem.find_by(name: params[:game][:gaming_system])
    @game.dm = current_user
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
        flash.now[:danger] = "Error creating game: #{@game.errors.full_messages.join(", ")}"
      render :new
    end
  end

  def edit
    @gaming_systems = GamingSystem.order(priority: :desc, name: :asc)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, notice: "Game was successfully deleted."
  end

  private

    def game_params
        params.require(:game).permit(:title, :description, :age_restriction, :application_process, 
        :price, :duration, :seats, :experience, :gaming_system, :power_level, :free, :recurrence_type,
        :next_game, :schedule)
    end
end

app/helpers/games_helper.rb
module GamesHelper
    def cover_image_tag(record, variant: [300, 300], default: "placeholder.jpg", **options)
        if record.cover_image.attached?
          image_tag record.cover_image.variant(resize_to_limit: variant), **options
        else
          image_tag default, **options
        end
      end
end

app/views/games/_game_preview.html.erb
<div class="game">
    <h2><%= game.title %></h2>
    <div class="row">
        <div class="col-md-3">
            <%= cover_image_tag(game, height: "200", class: 'img-fluid rounded') %>
        </div>
        <div class="col-md-9">
            <p>
                <%= game.description.truncate(500) %><br>
                <strong>Age Restriction:</strong> <%= game.age_restriction %><br>
                <strong>Recurrence:</strong> <%= game.recurrence %><br>
                <strong>Next game:</strong> <%= game.next_game.strftime("%B %d, %Y") %><br>
                <strong>Time:</strong> <%= game.game_time.strftime("%I:%M %p") %><br>
                <strong>Duration:</strong> <%= pluralize(game.duration, 'hour') %><br>
                <strong>Price:</strong> <%= game.price.to_i.zero? ? 'Free' : number_to_currency(game.price) %><br>
                <strong>Seats:</strong> <%= game.occupied_seats %> / <%= game.seats %><br>
                <%= link_to 'Show', game_path(game), class: 'btn btn-info' %>
                <% if user_signed_in? && current_user == game.dm %>
                    <%= link_to 'Edit', edit_game_path(game), class: 'btn btn-warning' %>
                    <%= link_to 'Delete', game_path(game), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                <% end %>
            </p>
        </div>
    </div>
</div>

app/views/games/_search_form.html.erb
<%= search_form_for @q, url: games_path, method: :get, html: { class: "form-inline" } do |f| %>
    <div class="form-group">
      <%= f.label :title_or_description_cont, "Search games" %>
      <%= f.search_field :title_or_description_cont, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= f.label :gaming_system_id_eq, "System" %>
      <%= f.select :gaming_system_id_eq,
            options_from_collection_for_select(@gaming_systems, :id, :name, f.object.gaming_system_id_eq),
            include_blank: "Any",
            class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= f.label :age_restriction_eq, "Age Rating" %>
      <%= f.select :age_restriction_eq,
            options_for_select(@age_restrictions, f.object.age_restriction_eq),
            include_blank: false,
            class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :recurrence_eq, "Recurrence" %>
      <%= f.select :recurrence_eq,
            options_for_select(@recurrences, f.object.recurrence_eq),
            id: 'recurrence-select',
            include_blank: false,
            class: "form-control" %>
    </div>
    <div id ='next-game-field' class="form-group", style="display: none">
    <div class="form-group">
      <%= f.label :next_game_date_gteq, "Earliest Date" %>
      <%= f.date_field :next_game_gteq, class: "form-control", value: @q.next_game_gteq || Time.now %>
    </div>
  
    <div class="form-group">
      <%= f.label :next_game_date_lteq, "Latest Date" %>
      <%= f.date_field :next_game_lteq, class: "form-control", value:  @q.next_game_lteq || Time.now + 30.days %>
    </div>
    </div>
  
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<h1>Games#index</h1>

<%= render partial: 'search_form' %>

<% @games.each do |game| %>
  <%= render partial: 'game_preview', locals: { game: game } %>
<% end %>
<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>Create a game</h1>

<%= form_with(model: @game, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <%# The form will be submitted via AJAX (remote: true) and will use the Bootstrap framework for styling. %>
    <div class="form-group">
        <%= form.label :title, class: 'control-label' %>
        <%= form.text_field :title, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= form.label :description, class: 'control-label' %>
        <%= form.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :age_restriction, class: 'control-label' %>
        <%= form.select :age_restriction, ['12+', '16+', '18+'], {}, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :free, class: 'control-label' %>
        <%= form.check_box :free, class: 'form-control form-check-input' %>
        <%= form.label :price, class: 'control-label' %>
        # Non free games; price at least 10, step 5
        <%= form.number_field :price, class: 'form-control', step: 5, min: 10, default: 10 %>
    </div>

    <div class="form-group">
        <%= form.label :duration, class: 'control-label' %>
        <%= form.number_field :duration, class: 'form-control', step: 0.5, min: 0.5, default: 0.5 %>
    </div>
    <div class="form-group">
        <%= form.label :seats, class: 'control-label' %>
        <%= form.number_field :seats, class: 'form-control', step: 1, min: 1, default: 1 %>
    </div> 
    <div class="form-group">
        <%= form.label :experience, class: 'control-label' %>
        <%= form.select :experience, ['anyone', 'beginner', 'experienced'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= form.label :gaming_system, class: 'control-label' %>
  
    <%= form.select :gaming_system,
        grouped_options_for_select(
            @gaming_systems.group_by(&:group).transform_values { |systems| systems.map(&:name) },
            selected: form.object.gaming_system
        ),
        {},
        class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= form.label :power_level, class: 'control-label' %>
        <%= form.text_field :power_level, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= form.label :application_process, class: 'control-label' %>
        <%= form.text_area :application_process, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :recurrence, class: 'control-label' %>
        <%= form.select :recurrence, ['one-shot', 'weekly', 'play-by-post', 'other'], {}, class: 'form-control', id: 'recurrence-select' %>
    </div>

    <div class="form-group" id="next-game-field" style="display: none;">
        <%= form.label :next_game, class: 'control-label' %>
        <%= form.date_field :next_game, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= form.submit 'Create Game', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/games/show.html.erb
<div class="row">
    <div class="col-md-8">
        <%= @game.description %><br>
        <strong>Age Restriction:</strong> <%= @game.age_restriction %><br>
        <strong>Recurrence:</strong> <%= @game.recurrence %><br>
        <strong>Next @game:</strong> <%= @game.next_game.strftime("%B %d, %Y") %><br>
        <strong>Time:</strong> <%= @game.game_time.strftime("%I:%M %p") %><br>
        <strong>Duration:</strong> <%= pluralize(@game.duration, 'hour') %><br>
        <strong>Price:</strong> <%= @game.price.to_i.zero? ? 'Free' : number_to_currency(@game.price) %><br>
        <strong>Seats:</strong> <%= @game.occupied_seats %> / <%= @game.seats %><br>
        <% if user_signed_in? && current_user == @game.dm %>
            <h3>Manage Game</h3>
            <%= render 'join_requests/join_requests', locals: { join_requests: @game.join_requests } %>
            <%= link_to 'Edit', edit_game_path(@game), class: 'btn btn-warning' %>
            <%= link_to 'Delete', game_path(@game), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
        <% if user_signed_in? && current_user != @game.dm %>
            <h3>Apply to Join</h3>
            <%= form_with model: JoinRequest.new, url: game_join_requests_path(@game), local: true do |f| %>
                <div class="form-group">
                <%= f.label :message, "Why do you want to join this game?" %>
                <%= f.text_area :message, class: "form-control", rows: 5 %>
                </div>
                <%= f.submit "Submit Request", class: "btn btn-primary" %>
            <% end %>
        <% end %>
    </div>
    <div class="col-md-4">
        <% if @dm %>
            <h4>Dungeon Master</h4>
            <p><strong>Name:</strong> <%= @dm.name %></p>
            <% if @dm.avatar.attached? %>
                <%= image_tag @dm.avatar.variant(:thumb), class: 'img-fluid rounded' %>
            <% else %>
                <%= image_tag 'avatar_placeholder.png', class: 'img-fluid rounded' %>
            <% end %>
            <p><strong>Bio</strong>: <%= @dm.bio %></p>
            <% if user_signed_in? && current_user != @dm %>
                <%= button_to 'Message Dungeon Master', private_message_path(dm_id: @dm.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
        <% else %>
            <h4>No Dungeon Master Assigned</h4>
        <% end %>
    </div>
</div>