config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "games#index"
  resources :games
  devise_scope :user do 
    get 'users/:id', to: 'users#show', as: 'user_profile'
  end

  resources :chat_rooms, only: [:show, :index]
  post :private_message, to: 'chat_rooms#private_message'
  resources :chat_messages, only: [:create]
  resources :games do
    resources :join_requests do
      member do
        post :create
        patch :accept
        patch :reject
      end
    end
    # post 'accept_join_request/:id', to: 'join_requests#accept', as: 'accept_join_request'
    # post 'reject_join_request/:id', to: 'join_requests#reject', as: 'reject_join_request'
  end
end

app/views/layouts/_navbar.html.erb
<div class="centered-container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Dmfinder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', games_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <div class="navbar-text">Welcome, <%= link_to "#{current_user.name}", user_profile_path(current_user.id) %>!</span>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Game', new_game_path, class: 'nav-link' %>
          </li>
          
        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dmfinder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
        <%= value %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>